In [1]:
#튜플의 기본 구조
data = ("사과", "배", "포도", "토마토", "딸기")

print(data)
print(type(data))

('사과', '배', '포도', '토마토', '딸기')
<class 'tuple'>


In [2]:
data[0] = 100

TypeError: 'tuple' object does not support item assignment

In [3]:
data = (100, 200, 100, 300, 100, 500)
print(type(data))
#튜플은 count함수를 이용해 해당 데이터의 개수를 확인가능함
print(data.count(100))

<class 'tuple'>
3


In [4]:
data = (100, 200, 100, 300, 100, 500)
print(type(data))

#튜플은 리스트와 같이 데이터의 슬라이싱이 가능
print(data[2:4])

<class 'tuple'>
(100, 300)


In [5]:
data1 = ("사과", "배", "포도", "토마토", "딸기")
data2 = (100, 200, 300, 400, 500)

#두 개의 튜플데이터를 덧셈연산자를 통해 하나로 합침
data = data1 + data2
print(data)

('사과', '배', '포도', '토마토', '딸기', 100, 200, 300, 400, 500)


In [6]:
data = ("사과", "배", "포도", "토마토", "딸기")

#튜플 데이터는 곱셈연산자를 이용해 데이터를 반복할 수 있음
print(data*2)

('사과', '배', '포도', '토마토', '딸기', '사과', '배', '포도', '토마토', '딸기')


In [7]:
data = {100, 200, 300}
print(data)
print(type(data))

{200, 100, 300}
<class 'set'>


In [8]:
data = {100, 200, 300, 400, 500, 600, 700}
print(data)
print(type(data))

#set 자료구조는 인덱싱과 슬라이싱이 불가능
data[0:4]

{100, 200, 300, 400, 500, 600, 700}
<class 'set'>


TypeError: 'set' object is not subscriptable

In [10]:
data = {100, 200, 300, 400, 500, 600}
print(data)

#세트 자료구조는 add함수를 이용해 데이터를 추가할 수 있음
data.add(700)
print(data)

{100, 200, 300, 400, 500, 600}
{100, 200, 300, 400, 500, 600, 700}


In [11]:
data = {100}
print("여러개의 데이터를 추가하기 전")
print(data)

print()
#세트 자료구조에서 여러개의 데이터를 추가할 때는 update함수를 이용해 추가
data.update([200, 300, 400, 500, 600])
print("여러개의 데이터를 추가한 후")
print(data)

여러개의 데이터를 추가하기 전
{100}

여러개의 데이터를 추가한 후
{100, 200, 300, 400, 500, 600}


In [12]:
data = {100, 200, 300, 400, 500, 600}
print("데이터를 삭제하기 전")
print(data)

print()
#세트 자료구조에서는 remove를 이용해 데이터를 제거
data.remove(600)
print("데이터를 삭제한 후")
print(data)

데이터를 삭제하기 전
{100, 200, 300, 400, 500, 600}

데이터를 삭제한 후
{100, 200, 300, 400, 500}


In [13]:
data = {100, 200, 300, 400, 500, 600}
print("데이터를 삭제하기 전")
print(data)

print()
#세트 자료구조에서 clear를 이용해 전체 데이터를 초기화
data.clear()
print(data)

데이터를 삭제하기 전
{100, 200, 300, 400, 500, 600}

set()


In [14]:
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))

#intersect함수는 교집합을 나타내는 함수
print()
print("intersection은 교집합을 나타내는 함수")
print(A.intersection(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

intersection은 교집합을 나타내는 함수
{200, 100, 300}


In [15]:
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))

#idifference함수는 차집합을 나타내는 함수
print()
print("difference은 차집합을 나타내는 함수")
print(A.difference(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

difference은 차집합을 나타내는 함수
{400, 500}


In [16]:
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))

#union함수는 합집합을 나타내는 함수
print()
print("union은 합집합을 나타내는 함수")
print(A.union(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

union은 합집합을 나타내는 함수
{100, 200, 300, 400, 500, 150, 250}


In [17]:
A = {100, 200, 300, 400, 500}
B = {100, 150, 200, 250, 300}
print(A)
print(type(A))
print(B)
print(type(B))

#symmetric_difference함수는 합집합에서 교집합을 뺀 나머지 집합을 나타내는 함수
print()
print("symmetric_difference함수는 합집합에서 교집합을 뺀 나머지 집합을 나타내는 함수")
print(A.symmetric_difference(B))

{100, 200, 300, 400, 500}
<class 'set'>
{100, 200, 300, 150, 250}
<class 'set'>

symmetric_difference함수는 합집합에서 교집합을 뺀 나머지 집합을 나타내는 함수
{400, 500, 150, 250}


In [20]:
dictionary = {
                'Name' : '홍길동',
                'Email' : 'gdHong@naver.com',
                '주소' : '서울시 광진구'
             }
type(dictionary)

dict

In [25]:
#딕셔너리(dictionary)의 기본 구조는 다음과 같이 표현할 수 있음
data = {"사과":300, "배":200, "포도":500, "딸기":700}
print(data)
print(type(data))

{'사과': 300, '배': 200, '포도': 500, '딸기': 700}
<class 'dict'>


In [26]:
#딕셔너리 데이터 예제를 data변수에 입력
data = {"사과":300, "배":200, "포도":500, "딸기":700}

#항목 검색할 때 항목의 키를 사용하면 됨
#위에서 키값 중 사과에 대한 값을 갖고 옴
print(data["사과"])

#위와 같이 표현도 가능하지만 아래와 같이 get함수를 이요해 효현도 가능
print(data.get("사과"))

300
300


In [27]:
#딕셔너리 데이터 예제를 data변수에 입력
data = {"사과":300, "배":200, "포도":500, "딸기":700}
print("추가하기 전 딕셔너리 전체 데이터")
print(data)

print()

#딕셔너리에 데이터를 추가할 때는 아래와 같이 키를 설정하고 값을 입력함
data["메론"] = 1000
print("추가한 후 딕셔너리 전체 데이터")
print(data)

추가하기 전 딕셔너리 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}

추가한 후 딕셔너리 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700, '메론': 1000}


In [28]:
#딕셔너리 데이터 예제를 data변수에 입력
data = {"사과":300, "배":200, "포도":500, "딸기":700}
print("추가하기 전 딕셔너리 전체 데이터")
print(data)

print()

#딕셔너리는 pop함수를 이용해 데이터를 삭제 가능
print("삭제한 후 딕셔너리 데이터")
data.pop("사과")
print(data)

추가하기 전 딕셔너리 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}

삭제한 후 딕셔너리 데이터
{'배': 200, '포도': 500, '딸기': 700}


In [30]:
#딕셔너리 데이터 예제를 data변수에 입력
data = {"사과":300, "배":200, "포도":500, "딸기":700}
print("추가하기 전 딕셔너리 전체 데이터")
print(data)

print()
#dorted는 항목을 정렬시키는 내장함수
print(sorted(data))

#value값을 이용해 정렬하고 싶으면 아래와 같이 실행
print()
print(sorted(data.values()))

추가하기 전 딕셔너리 전체 데이터
{'사과': 300, '배': 200, '포도': 500, '딸기': 700}

['딸기', '배', '사과', '포도']

[200, 300, 500, 700]


In [31]:
a = 100 #변수 a에 초기값으로 100을 저장

#변수 z가 100이라는 조건이 맞을 때 '일치'출력, 아니면 '불일치' 출력
if a == 100:
    print("일치")
else:
    print("불일치")

일치


In [32]:
a = 200 #변수 a에 초기값으로 200을 저장

#변수 z가 100이라는 조건이 맞을 때 '일치'출력, 아니면 '불일치' 출력
if a == 100:
    print("일치")
else:
    print("불일치")

불일치


In [34]:
#while문은 조건문에 만족할때까지 반복적으로 수행을 하지만
#중간에 break문을 사용해 강제로 while문을 종료하기도 함

a = 1 #변수 a에 초기값 1 저장

while a <=5: #while에 대한 조건문으로 변수 a의 값이 5이하가 될 때까지 반복
    print(a)   #변수 a 출력 
    a += 1    #변수 a에 1씩 더함

1
2
3
4
5


In [35]:
num_list = [1, 2, 3, 4, 5]  #리스트 구조변수 num_list에 1, 2, 3, 4, 5 값 저장

for num in num_list:
    print(num)

1
2
3
4
5


In [36]:
def f(x):
    #함수 f(x)를 생성하고 x의 값을 입력 받음
    #함수를 실핼했을 때 결과 값으로 x에 10을 더한 결과가 나오게 함
    return x + 10
f(2)

12

In [37]:
#함수와 lambda의 차이
def f(x):
    return x + 10

#일반적인 함수를 이용해 함수를 구현
print(f(10))

#lambda를 이용해 함수를 간단하게 구현
print((lambda x : x+10)(10))

20
20


In [38]:
def f(x):
    #하지만 변수가 없는 값을 입력했을 때는 에려 발생
    return y+10
f(2)

NameError: name 'y' is not defined

In [39]:
#Built-in 함수 중 대표함수인 input과 print
text = input("문장, 단어를 입력하세요:")
print(text)

문장, 단어를 입력하세요:Text
Text


In [41]:
np = [1, 0, 10.4, 3.2, 5.1, 7.5, 2.7] #변수 rp에 실수 list 생성

flotV = [np, np, np] #변수 floatV에 np list를 3개 넣어 다차원 배열 생성
flotV

[[1, 0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1, 0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1, 0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [43]:
#flotV는 다차원배열
#flotV[0]을 통해 n차원 배열 값 출력
flotV[0]

[1, 0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [45]:
flotV[0] = 'Python'  #flotV[0]의 차원에 위의 값 대신 'Python'값을 입력해 값을 변환
flotV

['Python', [1, 0, 10.4, 3.2, 5.1, 7.5, 2.7], [1, 0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [46]:
import numpy as np  #numpy패키지를 np라는 명칭으로 축약

a = np.array([1, 2.5, 4.0, 5.5, 7.0])
a[3:]

array([5.5, 7. ])

In [47]:
a.sum()  #rp.array로 생성한 변수 a의 합을 출력

20.0

In [48]:
a.std()  #rp.array로 생성한 변수 a의 표준편차을 출력

2.1213203435596424

In [49]:
a.cumsum()  #rp.array로 생성한 변수 a의 누적 합을 출력

array([ 1. ,  3.5,  7.5, 13. , 20. ])

In [52]:
print(a)             #변수 a의 값을 출력
print(a*2)           #변수 a의 값에 2를 곱한 것을 출력
print(a**2)          #변수 a의 값에 2를 제곱한 것을 출력
print(np.sqrt(a))    #변수 a의 값에 루트를 적용한 값을 출력

[1.  2.5 4.  5.5 7. ]
[ 2.  5.  8. 11. 14.]
[ 1.    6.25 16.   30.25 49.  ]
[1.         1.58113883 2.         2.34520788 2.64575131]


In [53]:
#변수 a의 값을 변수 b에 변환해 저장
#a**2는 변수 a의 값을 제공
b = np.array([a, a**2])
b

array([[ 1.  ,  2.5 ,  4.  ,  5.5 ,  7.  ],
       [ 1.  ,  6.25, 16.  , 30.25, 49.  ]])

In [55]:
b.sum(axis = 0)  #축(axis)이 0일 경우 세로 축의 합 출력

array([ 2.  ,  8.75, 20.  , 35.75, 56.  ])

In [56]:
b.sum(axis = 1)  #축(axis)이 1일 경우 가로 축의 합 출력

array([ 20. , 102.5])

In [58]:
np.array([[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0]])

In [60]:
#위의 배열선언과 다른 방법으로 같은 모양 배열 생성
#np.zeros를 통해 값을 설정하고 type를 설정해 배열을 생성 가능


values = np.zeros((2,3), dtype = 'i')  #dtype = i:정수형, dtype = f : 복소수형
values

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [61]:
import pandas as pd #pandas 패키지를 pd라는 명칭으로 축약해 호출
import numpy as np #numpy패키지를 np라는 명칭으로 축약해 호출

#Serise의 value와 index를 변수 pandas_series에 선언
pandas_series = pd.Series([3000, 3200, 2700],
                        index = ['2016-11-10', '2016-11-11', '2016-11-12'])
print(type(pandas_series))  #변수 pandas_series의 type 출력
pandas_series               #변수 pandas_series 실행

<class 'pandas.core.series.Series'>


2016-11-10    3000
2016-11-11    3200
2016-11-12    2700
dtype: int64

In [62]:
pandas_series[1:]

2016-11-11    3200
2016-11-12    2700
dtype: int64

In [63]:
import pandas as pd  #pandas 패키지를 pd라는 명칭으로 축약해 호출
import numpy as np   #numpy 패키지를 np라는 명칭으로 축약해 호출

#DataFrame의 value, column, index를 변수 df에 선언
df = pd.DataFrame([100,150,200,250,300], columns = ['numbers'], index = ['a','b','c','d','e'])
df

numbers
a      100
b      150
c      200
d      250
e      300

In [70]:
df.index  #DataFrame의 index를 표시

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [71]:
df.columns  #DataFrame의 column를 표시

Index(['numbers'], dtype='object')

In [74]:
df.ix['c']   #DataFrame의 index 중 c에 해당하는 값 출력

AttributeError: 'DataFrame' object has no attribute 'ix'

In [75]:
df.sum()  #DataFrame의 Value를 모두 더함

numbers    1000
dtype: int64

In [77]:
df.numbers**2  #DataFrame의 numbers 칼럼의 각 값을 제곱

a    10000
b    22500
c    40000
d    62500
e    90000
Name: numbers, dtype: int64

In [78]:
#DataFrame에 values라는 칼럼을 추가하고 값을 입력
df['values'] = (10,50,40,30,60)
df

numbers  values
a      100      10
b      150      50
c      200      40
d      250      30
e      300      60

In [81]:
#DataFrame의 index의 값에 일치하는 값을 넣음
df['values'] = pd.DataFrame(['Fourth' 'Second','First', 'Fifth', 'Third'], index = ['d', 'b', 'a' 'e', 'c'])
df

numbers        values
a      100           NaN
b      150         First
c      200         Third
d      250  FourthSecond
e      300           NaN

In [82]:
#DataFrame의 Values라는 칼럼을 삭제
del df['values']
df

numbers
a      100
b      150
c      200
d      250
e      300

In [83]:
df['values'] = (10,50,40) #DataFrame의 인덱스 수를 맞추지 않으면 에러 발생
df

ValueError: Length of values (3) does not match length of index (5)

In [85]:
#column A 에 1, 2, 3 값 넣음
df_1 = pd.DataFrame(['1', '2', '3'], columns = ['A'])

#column B 에 4, 5, 6, 7 값 넣음
df_2 = pd.DataFrame(['4', '5', '6', '7'], columns = ['B'])

df = df_1.join(df_2, how = 'outer')  #두 개의 DataFrame을 outer join으로 합침
df #합친 DataFrame 출력

A  B
0    1  4
1    2  5
2    3  6
3  NaN  7

In [86]:
import pandas as pd
import numpy as np

#random 값을 넣은 DataFrame 생성
#np.random.randn은 5행 5열의 랜덤 데이터를 생성
#재호출시 데이터가 변형되므로 주의
df = pd.DataFrame(np.random.randn(5,5))
df.columns = ['A', 'B', 'C', 'D', 'E']

df

A         B         C         D         E
0 -0.284509  0.690541 -0.471817 -0.355936  1.813454
1  0.989392 -0.222610 -0.469658 -0.855239  1.423816
2 -0.389147 -1.204169  1.200540  0.069767 -0.285007
3 -0.203459 -1.030624  0.774804 -0.534033  1.188128
4  0.595594 -1.713264 -0.066908 -2.242333  1.092627

In [87]:
#각 Column별 최대값 출력
df.max()

A    0.989392
B    0.690541
C    1.200540
D    0.069767
E    1.813454
dtype: float64

In [88]:
#각 Column별 최소값 출력
df.min()

A   -0.389147
B   -1.713264
C   -0.471817
D   -2.242333
E   -0.285007
dtype: float64

In [89]:
#각 Column별 평균값 출력
df.mean()

A    0.141574
B   -0.696025
C    0.193392
D   -0.783555
E    1.046604
dtype: float64

In [90]:
#각 Column별 표준편차 출력
df.std()

A    0.613838
B    0.942288
C    0.758664
D    0.881256
E    0.794620
dtype: float64

In [92]:
#각 Column별 누적합값 출력
df.cumsum()

A         B         C         D         E
0 -0.284509  0.690541 -0.471817 -0.355936  1.813454
1  0.704883  0.467931 -0.941476 -1.211175  3.237271
2  0.315736 -0.736238  0.259065 -1.141408  2.952264
3  0.112277 -1.766861  1.033868 -1.675441  4.140392
4  0.707871 -3.480125  0.966960 -3.917775  5.233019

In [93]:
#Describe함수를 이용해 DataFrame 데이터의 통계 요약값 표현
df.describe()

A         B         C         D         E
count  5.000000  5.000000  5.000000  5.000000  5.000000
mean   0.141574 -0.696025  0.193392 -0.783555  1.046604
std    0.613838  0.942288  0.758664  0.881256  0.794620
min   -0.389147 -1.713264 -0.471817 -2.242333 -0.285007
25%   -0.284509 -1.204169 -0.469658 -0.855239  1.092627
50%   -0.203459 -1.030624 -0.066908 -0.534033  1.188128
75%    0.595594 -0.222610  0.774804 -0.355936  1.423816
max    0.989392  0.690541  1.200540  0.069767  1.813454

In [94]:
#Group by 하기 전 그룹별로 구분하기 위해 division이라는 Column을 생성
df['division'] = ['X', 'Y', 'X', 'Y', 'Z']
df

A         B         C         D         E division
0 -0.284509  0.690541 -0.471817 -0.355936  1.813454        X
1  0.989392 -0.222610 -0.469658 -0.855239  1.423816        Y
2 -0.389147 -1.204169  1.200540  0.069767 -0.285007        X
3 -0.203459 -1.030624  0.774804 -0.534033  1.188128        Y
4  0.595594 -1.713264 -0.066908 -2.242333  1.092627        Z

In [95]:
#DataFrame에 Group by를 사용해 Colums division의 값에 따라 평균값을 산출
df.groupby(['division']).mean()

A         B         C         D         E
division                                                  
X        -0.336828 -0.256814  0.364361 -0.143084  0.764224
Y         0.392967 -0.626617  0.152573 -0.694636  1.305972
Z         0.595594 -1.713264 -0.066908 -2.242333  1.092627

In [96]:
a = [200,300,200,500,400,300,300]
print(a.count(300))

3
